library(qtl2)
iron <- read_cross2(file = system.file("extdata", "iron.zip", package="qtl2geno") )
map <- insert_pseudomarkers(map=iron$gmap, step=1)
pr <- calc_genoprob(cross=iron, map=map, error_prob=0.002)
Xcovar <- get_x_covar(iron)
out <- scan1(genoprobs = pr, pheno = iron$pheno, Xcovar=Xcovar)

png(filename = "lod-support.png", width = 600, height = 600)
plot_scan1(out, map = map, lodcolumn = "liver", chr = 16)
segments(x0 = 25, y0 = 6.18, x1 = 33, lty = 4, col = "red")
segments(x0 = 25, y0 = 0.5, x1 = 33, col = "red")
segments(x0 = 25, y0 = 0.25, y1 = 0.75, col = "red")
segments(x0 = 33, y0 = 0.25, y1 = 0.75, col = "red")
text(x = 30, y = 1.1, labels = "1.5 LOD support interval", cex = 0.75)
dev.off()